@startuml
partition "XORFork_ANDFork_a" {
    group "XORFork_ANDFork_a"
        #green:A;
        if (XOR) then (true)
            :B;
            fork
                :D;
            fork again
                :E;
            end fork
        else (false)
            :C;
        endif
        #red:F;
    end group
}
@enduml