@startuml
partition "loop break point" {
    group "loop break point"
        #green:A;
        repeat
            :B;
            if (XOR) then (true)
                    :C;
                    break
            else (false)
                    :D;
            endif
            :F;
        repeat while
        #red:E; 
    end group
}
@enduml