@startuml
partition "loop_with_2_breaks" {
    group "loop_with_2_breaks"
        #green:A;
        repeat
            :B;
            if (XOR) then (true)
                :C;
                break
            else (false)
                :D;
            endif
            if (XOR) then (true)
                :E;
                :F;
                :G;
                break
            else (false)
                :H;
            endif
        repeat while
        #red:I; 
    end group
}
@enduml