@startuml
    partition "find_and_add_loop_kill_paths_to_nested_graphs" {
        start
        :input DiGraph of Node's;
        group "main algorithm"
            :get all SubGraphNodes in graph;
            repeat
                :call "find_and_add_loop_kill_paths_to_subgraph_node" function;
                :recursively call "find_and_add_loop_kill_paths_to_nested_graphs" function with the sub graph;
            repeat while (for each SubGraphNode)
        end group
        end
        partition "sub algorithms" {
            start
            :input SubGraphNode;
            group "find_and_add_loop_kill_paths_to_subgraph_node"
                :get all kill edges from SubGraphNode.sub_graph using "get_all_kill_edges_from_loop_nodes_and_end_points" function;
                :convert kill edges to edges of uid to uid;
                :get the node to node map using "get_node_to_node_map_from_edges";
                :add loop kill paths to nodes using "add_loop_kill_paths_for_nodes";

            end group
            end
        }
    }
@enduml