@startuml
digraph G {
    rankdir=LR;
    subgraph clusterA {
        node [style=rounded];
        A [
            shape=record,
            label="{start=0 | end=10 }"
        ];
        B [
            shape=record,
            label="{start=5 | end=20}"
        ];
        C [
            shape=record,
            label="{start=15 | end=25}"
        ];
        label = "Async Group 1"
    }
        node [style=rounded];
        D [
            shape=record,
            label="{start=30 | end=40}"
        ];
    A -> D;
    B -> D;
    C -> D;
}
@enduml