ingest_data:
  data_source: json
  data_holder: sql
data_holders:
  sql:
    db_uri: 'sqlite:///:memory:'
    batch_size: 5
    time_buffer: 0
data_sources:
  json:
    dirpath: docs/example_otel_data
    filepath: null
    json_per_line: false
    field_mapping:
      job_name:
        key_paths: ["resource_spans.[].resource.attributes.[].key", "resource_spans.[].scope_spans.[].scope.name"]
        key_value: ["service.name", null]
        value_paths: ["value.Value.StringValue", null]
        value_type: string
      job_id:
        key_paths: ["resource_spans.[].scope_spans.[].spans.[].trace_id"]
        value_type: string
      event_type:
        key_paths: ["resource_spans.[].scope_spans.[].spans.[].name", "resource_spans.[].scope_spans.[].spans.[].attributes.[].key"]
        key_value: [null, http.status_code]
        value_paths: [null, value.Value.IntValue]
        value_type: string
      event_id:
        key_paths: [
            "resource_spans.[].scope_spans.[].spans.[].span_id"
        ]
        value_type: string
      start_timestamp:
        key_paths: ["resource_spans.[].scope_spans.[].spans.[].start_time_unix_nano"]
        value_type: string
      end_timestamp:
        key_paths: ["resource_spans.[].scope_spans.[].spans.[].end_time_unix_nano"]
        value_type: string
      application_name:
        key_paths: ["resource_spans.[].scope_spans.[].spans.[].attributes.[].key","resource_spans.[].resource.attributes.[].key"]
        key_value: [coral.service, service.version]
        value_paths: [value.Value.StringValue,value.Value.StringValue]
        value_type: string
      parent_event_id:
        key_paths: ["resource_spans.[].scope_spans.[].spans.[].parent_span_id"]
        value_type: string
      child_event_ids:
        key_paths: ["resource_spans.[].scope_spans.[].spans.[].child_span_ids"]
        value_type: array