data_sources:
  json:
    # Specify the file path to the JSON data
    dirpath: null
    filepath: path/to/json/file
    # Define the field mapping from the application to your JSON structure
    field_mapping:
      job_name:
        key_paths: [scope:name]
        value_type: string
      job_id:
        key_paths: [trace_id]
        value_type: string
      event_type:
        key_paths: [attributes::key, attributes::key]
        key_value: [http.method, http.status_code]
        value_paths: [value:Value:StringValue, value:Value:IntValue]
        value_type: string
      event_id:
        key_paths: [span_id]
        value_type: string
      start_timestamp:
        key_paths: [start_time_unix_nano]
        value_type: unix_nano
      end_timestamp:
        key_paths: [end_time_unix_nano]
        value_type: unix_nano
      application_name:
        key_paths: [attributes::key, resource:attributes::key]
        key_value: [coral.service, service.version]
        value_paths: [value:Value:StringValue, value:Value:StringValue]
        value_type: string
      parent_event_id:
        key_paths: [parent_span_id]
        value_type: string
      child_event_ids:
        key_paths: []

data_holders:
  sql:
    db_uri: sqlite:///graph_database.db
    batch_size: 100
    time_buffer: 15 # minutes

ingest_data:
  data_source: json
  data_holder: sql