data_sources:
  json:
    # dirpath takes precedent over filepath
    dirpath: /path/to/your/json/directory
    filepath: /path/to/your/json/file

data_holders:
  sql:
    db_uri: sqlite:///graph_database.db
    batch_size: 100
    time_buffer: 15 # minutes

ingest_data:
  data_source: json
  data_holder: sql