@startuml
    partition "branch_with_bunched_OR" {
        group "branch_with_bunched_OR"
            :A;
            :B,BCNT,user=B,name=BC1;
            ' :|||DUMMY|||;
            split
                :C;
            split again
                :D;
            end split
            :E;
        end group
    }
@enduml