@startuml
digraph G {
'   rankdir=LR;
  node [style=rounded];
  sequence_otel_jobs [label="sequence_otel_jobs"];
    sequence_otel_event_job [label="sequence_otel_event_job"];
    sequence_otel_jobs -> sequence_otel_event_job;
        sequence_otel_event_and_ancestors [label="sequence_otel_event_and_ancestors"];
        sequence_otel_event_job -> sequence_otel_event_and_ancestors;
            order_groups_by_start_timestamp [label="order_groups_by_start_timestamp"];
            sequence_otel_event_and_ancestors -> order_groups_by_start_timestamp;
            sequence_otel_event_and_ancestors -> sequence_otel_event_and_ancestors [label="recursion"];
            group_events_using_async_information [label="group_events_using_async_information"];
            sequence_otel_event_and_ancestors -> group_events_using_async_information;
            sequence_groups_of_otel_events_asynchronously [label="sequence_groups_of_otel_events_asynchronously"];
            sequence_otel_event_and_ancestors -> sequence_groups_of_otel_events_asynchronously;
                sequence_groups_of_otel_events_asynchronously -> order_groups_by_start_timestamp;
}
@enduml