@startuml
partition "multiple same event AND" {
    group "multiple same event AND"
        #green:A;
        :B,BCNT,user=B,name=BC1;
        repeat
        :C;
        repeat while (true)
        :D;
    end group
}
@enduml