ingest_data:
  data_source: json
  data_holder: sql

data_holders:
  sql:
    db_uri: "sqlite:///:memory:"
    batch_size: 5
    time_buffer: 30

data_sources:
  json:
    dirpath: dir/path/to/json/files
    filepath: null 
    field_mapping:
      job_name:
        key_paths:
          ["resource_spans.[].resource.attributes.[].key"]
        key_value: [service.name]
        value_paths: ["value.Value.StringValue"]
        value_type: string
      job_id:
        key_paths: ["resource_spans.[].scope_spans.[].spans.[].trace_id"]
        value_type: string
      event_type:
        key_paths: [
          [
            "resource_spans.[].scope_spans.[].spans.[].attributes.[].key",
            "resource_spans.[].scope_spans.[].spans.[].name"
          ],
          [
            "resource_spans.[].scope_spans.[].spans.[].attributes.[].key",
            "resource_spans.[].scope_spans.[].spans.[].kind"
          ],
        ]
        key_value: [[app.operation, null], [http.status_code, null]]
        value_paths: [[value:Value:StringValue, null], [value:Value:IntValue, null]]
        value_type: string
      event_id:
        key_paths: [span_id]
        value_type: string
      start_timestamp:
        key_paths: [start_time_unix_nano]
        value_type: string
      end_timestamp:
        key_paths: [end_time_unix_nano]
        value_type: string
      application_name:
        key_paths: ["resource_spans.[].scope_spans.[].scope.name"]
        value_type: string
      parent_event_id:
        key_paths: [parent_span_id]
        value_type: string