@startuml
partition "ANDFork_ANDFork_a" {
    group "ANDFork_ANDFork_a"
        #green:A;
        fork
            :B;
            fork
                :D;
            fork again
                :E;
            end fork
        fork again
            :C;
        end fork
        #red:F;
    end group
}
@enduml