@startuml
partition "branch_kill" {
    group "branch_kill"
        #green:A;
        fork
            :B;
            kill
        fork again
            :C;
            kill
        end fork
    end group
}
@enduml