@startuml
partition "bunched_XOR_switch" {
    group "bunched_XOR_switch"
        #green:A;
        switch (XOR)
            case ("1")
            if (XOR) then (true)
                if (XOR) then (true)
                    :B;
                else (false)
                    :C;
                endif
                :D;
            else
                :E;
            endif
            :F;
            case ("2")
            fork
                :G;
            fork again
                :H;
            end fork
            case ("3")
            :I;
        endswitch
        #red:J;
    end group
}
@enduml