@startuml
partition "simple_loop_with_break" {
    group "simple_loop_with_break"
        #green:A;
        repeat
            :B;
            if (XOR) then (true)
                :C;
                break
            else (false)
                :D;
                :E;
            endif
        repeat while
        #red:F; 
    end group
}
@enduml