name: Build and Push Zipapp Archive To Release
on:
  release:
    types: [published]

jobs:
  zipapp-amd-build-and-push:
    if: |
      github.repository == 'xtuml/otel2puml'
          && github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Create tel2puml.pyz
        run: ./scripts/build_zip_app.sh
      
      - name: Upload to GitHub Releases
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist/tel2puml.pyz
