name: run-tests
on: [workflow_call]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Actions
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python Dependencies
        run: |
          export PIP_CONSTRAINT='pip_constraint.txt'
          pip install --upgrade pip

          pip install flake8
          flake8 --version
          pip install pylint
          pylint --version
          pip install mypy
          mypy --version

          pip install -r requirements.txt
      
      - name: Install janus as package
        run: |
          chmod +x ./scripts/install_repositories.sh && ./scripts/install_repositories.sh

      - name: Flake8
        if: '!cancelled()'
        run: |
          PY_FILES=$(git ls-files '*.py')

          if [ -z "$PY_FILES" ]
          then
            echo "No files to check!"
          else
            flake8 $PY_FILES
          fi

      - name: Pylint
        if: '!cancelled()'
        run: |
          PY_FILES=$(git ls-files '*.py')

          if [ -z "$PY_FILES" ]
          then
            echo "No files to check!"
          else
            pylint $PY_FILES
          fi

      - name: MyPy
        if: '!cancelled()'
        run: |
          PY_FILES=$(git ls-files '*.py')

          if [ -z "$PY_FILES" ]
          then
            echo "No files to check!"
          else
            mypy --strict --explicit-package-bases --namespace-packages .
          fi