name: test-workflow
on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      'main'
  push:
    branches:
      main


jobs:
  sast:
    uses: SmartDCSITlimited/actions-store/.github/workflows/SAST.yml@main
  secret-detection:
    uses: SmartDCSITlimited/actions-store/.github/workflows/SecretDetection.yml@main
  python-linting:
    uses: ./.github/workflows/PythonLinting.yml

  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Checkout
        uses: actions/checkout@v4

      - name: Setup Checkout (test-event-generator)
        uses: actions/checkout@v4
        with:
          repository: SmartDCSITlimited/test-event-generator
          ssh-key: ${{ secrets.GH_CDS_TEST_EVENT_GENERATOR_GITHUB_WORKFLOW_KEY }}
          path: test-event-generator

      - name: Setup Checkout (test-harness)
        uses: actions/checkout@v4
        with:
          repository: SmartDCSITlimited/test-harness
          ssh-key: ${{ secrets.GH_CDS_TEST_HARNESS_GITHUB_WORKFLOW_KEY }}
          path: test-harness

      - name: Setup-conda
        uses: s-weigand/setup-conda@v1
        with:
          update-conda: true
          python-version: 3.11.8
          conda-channels: conda-forge

      - name: Install pre-requisites
        run: |
          conda install -y -c conda-forge cvxopt
          conda install -y -c conda-forge pygraphviz

      - name: Install Requirements (test-event-generator)
        run: |
          cd test-event-generator
          git fetch --all --tags
          git checkout tags/v1.0.1 -b latest
          pip install -r requirements.txt
          pip install .
          cd ..
          rm -rf test-event-generator

      - name: Install Requirements (test-harness)
        run: |
          cd test-harness
          git fetch --all --tags
          git checkout tags/v1.1.3 -b latest
          pip install -r requirements.txt
          pip install .
          cd ..
          rm -rf test-harness
      
      - name: Install Requirements
        run: |
          export PIP_CONSTRAINT='pip_constraint.txt'
          pip install --upgrade pip

          pip install pytest
          pytest --version

          pip install -r requirements.txt

      - name: Run Tests
        run: |
          export PYTHONPATH=/workspaces/test-harness:$PYTHONPATH
          pytest
