name: test-workflow
on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      'main'
  push:
    branches:
      main


jobs:
  sast:
    uses: SmartDCSITlimited/actions-store/.github/workflows/SAST.yml@main
  secret-detection:
    uses: SmartDCSITlimited/actions-store/.github/workflows/SecretDetection.yml@main
  python-linting:
    uses: ./.github/workflows/PythonLinting.yml

  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Checkout
        uses: actions/checkout@v4

      - name: Setup-conda
        uses: s-weigand/setup-conda@v1
        with:
          update-conda: true
          python-version: 3.11.8
          conda-channels: conda-forge

      - name: Install pre-requisites
        run: |
          conda install -y -c conda-forge cvxopt
          conda install -y -c conda-forge pygraphviz

      - name: Install janus and erebus as packages
        run: |
          chmod +x ./scripts/install_repositories.sh && ./scripts/install_repositories.sh
      
      - name: Add GitHub workspace to PYTHONPATH
        run: echo "PYTHONPATH=${GITHUB_WORKSPACE}" >> $GITHUB_ENV
      
      - name: Install Requirements
        run: |
          export PIP_CONSTRAINT='pip_constraint.txt'
          pip install --upgrade pip

          pip install pytest
          pytest --version

          pip install -r requirements.txt

      - name: Run Tests
        run: |
          pytest
