@startuml
partition "bunched_XORFork_ANDFork" {
    group "bunched_XORFork_ANDFork"
        #green:A;
        if (XOR) then (true)
            fork
                :D;
            fork again
                :E;
            end fork
            :B;
        else (false)
            :C;
        endif
        #red:F;
    end group
}
@enduml